version: "3.9"

services:

  app:
    build:
      context: .
    restart: always
    container_name: libary_music
    depends_on:
      - postgres
      - migrate
    networks:
      - library_net
    volumes:
      - .:/app


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: lib_music
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - library_net

  migrate:
    image: migrate/migrate
    container_name: migrate
    entrypoint: [ "sh", "-c", "./wait_for.sh postgres:5432 -- migrate -path /migrations -database postgres://lib_music:qwerty@postgres:5432/postgres?sslmode=disable up" ]
    depends_on:
      - postgres
    networks:
      - library_net
    volumes:
      - ./migrations:/migrations
      - ./wait_for.sh:/wait_for.sh




networks:
  library_net:
    driver: bridge

volumes:
  pg_data:
