CREATE TABLE music_band(
    music_band_id int generated by default as identity PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE  song (
                       song_id int generated by default as identity PRIMARY KEY,
                       music_band_id INT REFERENCES music_band(music_band_id) ON DELETE CASCADE,
                       title VARCHAR(255) NOT NULL,
                       release_date DATE,
                       lyrics TEXT,
                       link TEXT,
                       UNIQUE (music_band_id, title)
);

CREATE TABLE  verse (
                        verse_id int generated by default as identity PRIMARY KEY,
                        song_id INT REFERENCES song(song_id) ON DELETE CASCADE,
                        content TEXT,
                        position INT
);

